#include<iostream.h>
#include<conio.h>
void main()
{
	 int a,b,c,sum;
	 clrscr();
	 cout<<"******INPUT*****";
	 cout<<"\n";
	 cout<<"Enter the first number:-";
	 cin>>a;
	 cout<<"Enter the second number:-";
	 cin>>b;
	 cout<<"Enter the third number:-";
	 cin>>c;
	 sum=a+b+c;
	 cout<<"\n";
	 cout<<"******OUTPUT******";
	 cout<<"\n";
	 cout<<"The addition of two number is:-"<<sum;

	 getch();
}